### PR TITLE
Managed to fix the import bug

### PR DESCRIPTION
**Pull request by aFuzzyBear**
Hey friend, 

I managed to fix that bug, and thank you for letting me discover that gotcha, 

so basically there was a few things going on that was stopping the function from 
1) being bundled
2) being called

1) 
There is a few notes Ive made about this:
in `Fx.astro` the bundled module file, here the import address is the relative path to the project root, this is important
Secondly I had affixed this to the Head of the MainLayout, this way its called on the page and Astro picks it up, hoisting the library to the top, 
This means the library is readily available now to the page
2) 
Calling this there was a problem with the `animate(target,store)` here the store variable and the imported animate variables dont match up, this is a build transformation however the build step is correct in its assumptions so its more of a case of correctly pointing the store which is a global to be taken out the parameter call and also stripped out the FX call from inside the function as that was the last bug, corrected the references and now call the library as param works, 
🥳

### CODE REVIEW

**Comment by aFuzzyBear** [comment]
Two mins Ill finish of the rest of the script and it should be good to merge

**Comment by aFuzzyBear** [comment]
That should be good to go my friend =)

**Comment by sebiko3** [comment]
Looking good! Thanks :)

**Comment by aFuzzyBear** [comment]
no worries, now noticing a problem with the final build output, its not being bundled at all

**Pull request merged**
